# Generated by Django 6.0.1 on 2026-01-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingfile',
            name='file_name',
            field=models.FileField(upload_to='media/teaching_files/'),
        ),
    ]
