# Generated by Django 6.0.1 on 2026-01-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_teachingfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingfile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.subject'),
        ),
    ]
