# Generated by Django 6.0.1 on 2026-01-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_teachingfile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingfile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.subject'),
        ),
    ]
