# Generated by Django 6.0.1 on 2026-01-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_teachingfile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingfile',
            name='subject',
        ),
    ]
