# Generated by Django 6.0.1 on 2026-01-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_teachingfile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingfile',
            name='semester',
            field=models.CharField(blank=True, help_text='Auto-filled from XLSB file when parsed', max_length=50, null=True),
        ),
    ]
