# Generated by Django 6.0.1 on 2026-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_teachingfile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingsession',
            name='lecture_type',
            field=models.CharField(blank=True, help_text='Type of lecture (e.g., Introduction, Lab, Tutorial)', max_length=200, null=True, verbose_name='Lecture Type'),
        ),
    ]
