# Generated by Django 6.0.1 on 2026-01-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_teachingsession_lecture_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingsession',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['lecturer', 'date'], name='analytics_t_lecture_914903_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['subject', 'date'], name='analytics_t_subject_bb51ec_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['date', 'time_in'], name='analytics_t_date_992e59_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachingsession',
            constraint=models.UniqueConstraint(fields=('lecturer', 'subject', 'date', 'time_in', 'time_out'), name='unique_session_timeslot'),
        ),
    ]
