# Generated by Django 6.0.1 on 2026-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_teachingsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingfile',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
