# Generated by Django 6.0.1 on 2026-01-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_teachingfile_is_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', help_text='e.g., YYYY-MM-DD, DD/MM/YYYY', max_length=20)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('records_per_page', models.PositiveSmallIntegerField(default=10)),
                ('default_columns', models.CharField(default='subject,date,duration,lecture_type', help_text='Comma-separated list of default columns for teaching records table', max_length=255)),
                ('default_sort_order', models.CharField(default='-date', help_text='Default sort order for teaching records (e.g., -date, subject__name)', max_length=50)),
                ('workload_display', models.CharField(choices=[('weekly', 'Weekly Hours'), ('monthly', 'Monthly Hours'), ('semester', 'Per Semester')], default='weekly', max_length=20)),
                ('workload_target', models.PositiveSmallIntegerField(default=15, help_text='Weekly workload target in hours')),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='analytics.lecturer')),
            ],
        ),
    ]
