# Generated by Django 6.0.1 on 2026-01-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_lecturersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturersettings',
            name='default_columns',
            field=models.CharField(default='date,subject,lecture_type,time_in,time_out,duration,source_file', help_text='Comma-separated list of default columns for teaching records table', max_length=255),
        ),
    ]
