# Generated by Django 6.0.1 on 2026-01-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_lecturersettings_default_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('file_upload', 'File Upload'), ('file_parse', 'File Parse'), ('file_error', 'File Error'), ('session_reminder', 'Session Reminder'), ('workload_alert', 'Workload Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=200, null=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analytics.lecturer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lecturer', 'is_read', '-created_at'], name='analytics_n_lecture_eacba8_idx')],
            },
        ),
    ]
