# Generated by Django 6.0.1 on 2026-01-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='analytics_n_lecture_eacba8_idx',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the lecturer was approved', null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this lecturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lecturers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before lecturer can access the system'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
