# Generated by Django 6.0.1 on 2026-01-17 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_remove_notification_analytics_n_lecture_eacba8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('default_date_format', models.CharField(default='YYYY-MM-DD', help_text='e.g., YYYY-MM-DD, DD/MM/YYYY', max_length=20)),
                ('default_records_per_page', models.PositiveSmallIntegerField(default=15)),
                ('default_workload_target', models.PositiveSmallIntegerField(default=20, help_text='Default weekly workload target in hours for new lecturers.')),
                ('risk_threshold_overload', models.PositiveSmallIntegerField(default=125, help_text="Percentage above target to be considered 'Overload' (e.g., 125%).")),
                ('risk_threshold_underload', models.PositiveSmallIntegerField(default=75, help_text="Percentage below target to be considered 'Underload' (e.g., 75%).")),
                ('allowed_file_types', models.CharField(default='.xlsb,.zip', help_text='Comma-separated list of allowed file extensions.', max_length=100)),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=15, help_text='Maximum file size in MB.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
