# Generated by Django 6.0.1 on 2026-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='semester_workload_target',
            field=models.PositiveSmallIntegerField(default=180, help_text='Target workload in hours for the entire semester.'),
        ),
    ]
