# Generated by Django 6.0.1 on 2026-01-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_adminsettings_semester_workload_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturersettings',
            name='workload_target',
        ),
    ]
