# Generated by Django 6.0.1 on 2026-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_lecturersettings_workload_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='default_columns',
            field=models.JSONField(default=list),
        ),
    ]
