# Generated by Django 6.0.1 on 2026-01-18 03:43

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_adminsettings_default_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='default_columns',
            field=models.JSONField(default=analytics.models.get_default_admin_columns),
        ),
    ]
